Extension { #name : #LeExportTextSnippetAnnotationVisitor }

{ #category : #'*Leibniz2' }
LeExportTextSnippetAnnotationVisitor >> visitTopLevelEqualityAxiom: aLzTopLevelEqualityAxiomNode [
]

{ #category : #'*Leibniz2' }
LeExportTextSnippetAnnotationVisitor >> visitTopLevelFunctionRule: aLzTopLevelFunctionRuleNode [
]

{ #category : #'*Leibniz2' }
LeExportTextSnippetAnnotationVisitor >> visitTopLevelOp: aLzTopLevelOpNode [
]

{ #category : #'*Leibniz2' }
LeExportTextSnippetAnnotationVisitor >> visitTopLevelTerm: aLzTopLevelTermNode [
]

{ #category : #'*Leibniz2' }
LeExportTextSnippetAnnotationVisitor >> visitTopLevelUseContext: aLzTopLevelUseContextNode [
]
