Extension { #name : #LeExportVisitor }

{ #category : #'*Leibniz2' }
LeExportVisitor >> visitTopLevelEqualityAxiom: aLzTopLevelEqualityAxiomNode [
]

{ #category : #'*Leibniz2' }
LeExportVisitor >> visitTopLevelFunctionRule: aLzTopLevelFunctionRuleNode [
]

{ #category : #'*Leibniz2' }
LeExportVisitor >> visitTopLevelOp: aLzTopLevelOpNode [
]

{ #category : #'*Leibniz2' }
LeExportVisitor >> visitTopLevelTerm: aLzTopLevelTermNode [
]

{ #category : #'*Leibniz2' }
LeExportVisitor >> visitTopLevelUseContext: aLzTopLevelUseContextNode [
]
