Extension { #name : #LeHtmlTextSnippetPostAbstractVisitor }

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetPostAbstractVisitor >> visitTopLevelEqualityAxiom: aLzTopLevelEqualityAxiomNode [
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetPostAbstractVisitor >> visitTopLevelFunctionRule: aLzTopLevelFunctionRuleNode [
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetPostAbstractVisitor >> visitTopLevelOp: aLzTopLevelOpNode [
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetPostAbstractVisitor >> visitTopLevelTerm: aLzTopLevelTermNode [
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetPostAbstractVisitor >> visitTopLevelUseContext: aLzTopLevelUseContextNode [
]
