Extension { #name : #LeHtmlTextSnippetAnnotationPostAbstractVisitor }

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationPostAbstractVisitor >> visitTopLevelEqualityAxiom: aLzTopLevelEqualityAxiomNode [
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationPostAbstractVisitor >> visitTopLevelFunctionRule: aLzTopLevelFunctionRuleNode [
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationPostAbstractVisitor >> visitTopLevelOp: aLzTopLevelOpNode [
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationPostAbstractVisitor >> visitTopLevelTerm: aLzTopLevelTermNode [
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationPostAbstractVisitor >> visitTopLevelUseContext: aLzTopLevelUseContextNode [
]
