Extension { #name : #LeHtmlTextSnippetAnnotationVisitor }

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationVisitor >> visitTopLevelEqualityAxiom: aLzTopLevelEqualityAxiomNode [
	LzHTMLTextSnippetAnnotationWriter new
		snippet: snippet;
		context: context;
		annotation: aLzTopLevelEqualityAxiomNode;
		write
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationVisitor >> visitTopLevelFunctionRule: aLzTopLevelFunctionRuleNode [
	LzHTMLTextSnippetAnnotationWriter new
		snippet: snippet;
		context: context;
		annotation: aLzTopLevelFunctionRuleNode;
		write
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationVisitor >> visitTopLevelOp: aLzTopLevelOpNode [
	LzHTMLTextSnippetAnnotationWriter new
		snippet: snippet;
		context: context;
		annotation: aLzTopLevelOpNode;
		write
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationVisitor >> visitTopLevelRewriteRule: aLzTopLevelRewriteRuleNode [
	LzHTMLTextSnippetAnnotationWriter new
		snippet: snippet;
		context: context;
		annotation: aLzTopLevelRewriteRuleNode;
		write
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationVisitor >> visitTopLevelSort: aLzTopLevelSortNode [
	LzHTMLTextSnippetAnnotationWriter new
		snippet: snippet;
		context: context;
		annotation: aLzTopLevelSortNode;
		write
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationVisitor >> visitTopLevelSpecialTerms: aLzTopLevelSpecialTermsNode [
	LzHTMLTextSnippetAnnotationWriter new
		snippet: snippet;
		context: context;
		annotation: aLzTopLevelSpecialTermsNode;
		write
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationVisitor >> visitTopLevelSubsort: aLzTopLevelSubsortNode [
	LzHTMLTextSnippetAnnotationWriter new
		snippet: snippet;
		context: context;
		annotation: aLzTopLevelSubsortNode;
		write
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationVisitor >> visitTopLevelTerm: aLzTopLevelTermNode [
	LzHTMLTextSnippetAnnotationWriter new
		snippet: snippet;
		context: context;
		annotation: aLzTopLevelTermNode;
		write
]

{ #category : #'*Leibniz2' }
LeHtmlTextSnippetAnnotationVisitor >> visitTopLevelUseContext: aLzTopLevelUseContextNode [
	LzHTMLTextSnippetAnnotationWriter new
		snippet: snippet;
		context: context;
		annotation: aLzTopLevelUseContextNode;
		write
]
