Class {
	#name : #LzColors,
	#superclass : #Object,
	#category : #'Leibniz2-Infrastructure'
}

{ #category : #accessing }
LzColors class >> declarationColor [
	^ Color blue
]

{ #category : #accessing }
LzColors class >> exampleColor [
	^ Color brown
]

{ #category : #accessing }
LzColors class >> resultColor [
	^ Color green muchDarker
]

{ #category : #accessing }
LzColors class >> subcontextColor [
	^ Color purple
]
